import type { Config } from '../index.js';
import type { ApiKeyStatus } from '../api-key.js';
import type { EngineControlStatus } from '../host-routes.js';
import type { EngineReleaseStatus, InstalledEngine } from '../engine-release.js';
import type { ModelDownloadProgress, RecommendedModel } from '../model-download.js';
import type { LocalModelLibrary, ModelFileKind } from '../model-files.js';
import type { Moe4AllSettingsProps } from './Moe4AllSettings.js';
import { type Editor } from './workspace-model.js';
export declare const isInstalling: (release: EngineReleaseStatus | null) => boolean;
export declare function useWorkspace(props: Moe4AllSettingsProps): {
    editor: {
        config: Config;
        setup: import("./engine-setup.js").ParsedEngineArguments;
        context: string;
        maxTokens: string;
        extras: string[];
        extraText: string | undefined;
    } | null;
    baseline: {
        config: Config;
        setup: import("./engine-setup.js").ParsedEngineArguments;
        context: string;
        maxTokens: string;
        extras: string[];
        extraText: string | undefined;
    } | null;
    dirty: boolean;
    edit: (update: (previous: Editor) => Editor) => void;
    config: (patch: Partial<Config>) => void;
    setup: (patch: Partial<Editor["setup"]>) => void;
    status: EngineControlStatus | null;
    release: EngineReleaseStatus | null;
    catalog: RecommendedModel[];
    library: LocalModelLibrary;
    download: ModelDownloadProgress;
    directory: string;
    directories: string[];
    nativePicker: boolean;
    apiKey: ApiKeyStatus | null;
    working: string;
    scanning: boolean;
    error: string;
    notice: string;
    setError: import("react").Dispatch<import("react").SetStateAction<string>>;
    setNotice: import("react").Dispatch<import("react").SetStateAction<string>>;
    resourcePrompt: boolean;
    setResourcePrompt: import("react").Dispatch<import("react").SetStateAction<boolean>>;
    portPrompt: boolean;
    setPortPrompt: import("react").Dispatch<import("react").SetStateAction<boolean>>;
    portCandidate: string;
    setPortCandidate: import("react").Dispatch<import("react").SetStateAction<string>>;
    disabled: boolean;
    snapshot: import("@deepseek-ai/dsh-client-runtime/client").SettingsScopeSnapshot<Config>;
    scan: () => Promise<boolean>;
    save: () => Promise<boolean>;
    launch: (force?: boolean, restart?: boolean) => Promise<boolean>;
    launchAtPort: (port: number) => Promise<boolean>;
    stop: () => Promise<boolean>;
    refresh: () => Promise<boolean>;
    saveApiKey: (value: string) => Promise<boolean>;
    regenerateApiKey: () => Promise<boolean>;
    selectEngine: (engine: InstalledEngine) => void;
    install: (localPath?: string) => Promise<void>;
    checkUpdates: () => Promise<boolean>;
    removeVersion: (engine: InstalledEngine) => Promise<boolean>;
    stopInstall: () => Promise<boolean>;
    selectModel: (path: string, kind: ModelFileKind) => void;
    importPath: (path: string, kind?: ModelFileKind) => Promise<boolean>;
    pickFile: (kind?: ModelFileKind) => Promise<boolean>;
    pickDownloadDirectory: () => Promise<boolean>;
    addDiscoveryDirectory: () => Promise<boolean>;
    removeDiscoveryDirectory: (path: string) => Promise<boolean>;
    downloadModel: (model: RecommendedModel) => Promise<boolean>;
    stopDownload: () => Promise<boolean>;
    revert: () => void;
};
export type Workspace = ReturnType<typeof useWorkspace>;
//# sourceMappingURL=use-workspace.d.ts.map