declare const copy: {
    readonly runTab: readonly ["Run", "运行"];
    readonly parallel: readonly ["Concurrent slots", "并发会话数"];
    readonly modelsTab: readonly ["Model library", "模型库"];
    readonly rescanModels: readonly ["Rescan local models", "重新扫描本地模型"];
    readonly openModelSource: readonly ["Open model source", "打开模型来源"];
    readonly advancedOverride: readonly ["Manual values override the selected preset.", "手动填写的参数优先于自动策略。"];
    readonly enginesTab: readonly ["Engine versions", "引擎版本"];
    readonly diagnosticsTab: readonly ["Diagnostics", "诊断"];
    readonly localRun: readonly ["Run on this computer", "在本机运行"];
    readonly existingService: readonly ["Connect to a service", "连接已有服务"];
    readonly notConfigured: readonly ["Not configured", "尚未配置"];
    readonly readyStatus: readonly ["Ready", "已就绪"];
    readonly startingStatus: readonly ["Starting", "正在启动"];
    readonly stoppedStatus: readonly ["Stopped", "未运行"];
    readonly failedStatus: readonly ["Startup failed", "启动失败"];
    readonly checkingStatus: readonly ["Checking connection", "正在检查连接"];
    readonly busyStatus: readonly ["Confirmation needed", "等待确认"];
    readonly duplicateStatus: readonly ["Engine already running elsewhere", "检测到其他引擎进程"];
    readonly pluginOwned: readonly ["Started here", "由插件启动"];
    readonly externalOwned: readonly ["Existing service", "已有服务"];
    readonly setupTitle: readonly ["Get ready to run", "准备开始"];
    readonly stepEngine: readonly ["Install an engine", "准备引擎"];
    readonly stepModel: readonly ["Choose a model", "选择模型"];
    readonly stepStart: readonly ["Start chatting", "启动使用"];
    readonly firstInstallRunning: readonly ["Preparing the MoE4All engine", "正在准备 MoE4All 引擎"];
    readonly firstInstallRunningBody: readonly ["The official release is downloading and will be configured automatically. You can leave this page open.", "正在下载官方发行版，完成后会自动配置。保持此页面打开即可。"];
    readonly firstInstallAttention: readonly ["Engine setup needs attention", "引擎安装需要处理"];
    readonly firstInstallAttentionBody: readonly ["Retry the automatic download, or import a ZIP, folder, or infr.exe you already downloaded.", "可以重试自动下载，或导入已经下载的 ZIP、目录或 infr.exe。"];
    readonly modelEmpty: readonly ["No model selected", "尚未选择模型"];
    readonly selectedModelTitle: readonly ["Selected model", "当前模型"];
    readonly browseLibrary: readonly ["Choose a model", "选择模型"];
    readonly importModel: readonly ["Add local model", "添加本地模型"];
    readonly useSelected: readonly ["Use model", "使用此模型"];
    readonly usingModel: readonly ["Selected", "已选用"];
    readonly changeModel: readonly ["Change", "更换"];
    readonly optionalFeatures: readonly ["Optional capabilities", "可选能力"];
    readonly essential: readonly ["Common settings", "常用设置"];
    readonly performance: readonly ["Performance preset", "性能策略"];
    readonly balancedLabel: readonly ["Balanced", "稳健自动"];
    readonly performanceLabel: readonly ["Performance", "激进自动"];
    readonly balancedHelp: readonly ["Uses currently available memory with headroom.", "按当前空余内存与显存分配，保留余量。"];
    readonly performanceHelp: readonly ["Uses larger budgets based on total memory.", "按总内存与总显存规划更大的预算。"];
    readonly automatic: readonly ["Automatic", "自动"];
    readonly startupPolicy: readonly ["When DSH opens", "打开 DSH 时"];
    readonly askStart: readonly ["Ask before starting", "询问是否启动"];
    readonly autoStart: readonly ["Start automatically", "自动启动"];
    readonly resourcesHelp: readonly ["A second confirmation is required when resources fall below the threshold.", "资源低于警戒线时，启动仍需再次确认。"];
    readonly advancedOptions: readonly ["Advanced parameters", "高级参数"];
    readonly memoryCompute: readonly ["Memory & compute", "内存与计算"];
    readonly deviceLabel: readonly ["GPU device", "GPU 设备"];
    readonly ramLabel: readonly ["RAM budget", "RAM 预算"];
    readonly vramLabel: readonly ["VRAM budget", "VRAM 预算"];
    readonly threadsLabel: readonly ["CPU threads", "CPU 线程"];
    readonly batchLabel: readonly ["Prefill micro-batch", "Prefill Ubatch"];
    readonly splitterLabel: readonly ["Dispatch cap", "Dispatch 上限"];
    readonly cacheSection: readonly ["Conversation cache", "会话缓存"];
    readonly cacheEnabled: readonly ["Reuse conversations from SSD", "复用 SSD 会话缓存"];
    readonly kvQuantization: readonly ["KV cache precision", "KV Cache 量化"];
    readonly kvQuantizationHelp: readonly ["Lower precision saves VRAM. Engine automatic follows the selected resource profile.", "更低精度可节省显存；引擎自动会跟随所选资源策略。"];
    readonly kvCustom: readonly ["Custom K / V", "分别指定 K / V"];
    readonly kvKeyType: readonly ["K cache type", "K Cache 类型"];
    readonly kvValueType: readonly ["V cache type", "V Cache 类型"];
    readonly sessionCacheKvHint: readonly ["SSD conversation cache requires Q8_0 K and V, so Q8_0 is used while it is enabled.", "SSD 会话缓存要求 K、V 均为 Q8_0，启用期间会固定使用 Q8_0。"];
    readonly networkSection: readonly ["Network & connection", "网络与连接"];
    readonly samplingSection: readonly ["Generation defaults", "生成默认值"];
    readonly temperatureLabel: readonly ["Temperature", "温度"];
    readonly customArguments: readonly ["Additional engine arguments", "额外引擎参数"];
    readonly launchPreview: readonly ["Launch command", "启动命令预览"];
    readonly modelDirectoryLabel: readonly ["Model storage", "模型存放目录"];
    readonly searchModels: readonly ["Search models or quantization", "搜索模型或量化"];
    readonly filterAll: readonly ["All", "全部"];
    readonly filterLocal: readonly ["On this computer", "本地"];
    readonly filterRecommended: readonly ["Recommended", "推荐"];
    readonly availableLocal: readonly ["Local", "本地可用"];
    readonly incompleteModel: readonly ["Missing shards", "分片不完整"];
    readonly noMatches: readonly ["No matching models", "没有匹配的模型"];
    readonly noLocalModels: readonly ["No local models yet", "尚未添加本地模型"];
    readonly importPath: readonly ["File or folder path", "文件或目录路径"];
    readonly addPath: readonly ["Add", "添加"];
    readonly modelRoleMain: readonly ["Language model", "语言模型"];
    readonly modelRoleVision: readonly ["Vision", "视觉"];
    readonly modelRoleMtp: readonly ["MTP", "MTP"];
    readonly modelRoleEmbedding: readonly ["Embedding", "Embedding"];
    readonly downloadAction: readonly ["Download", "下载"];
    readonly continueDownload: readonly ["Continue download", "继续下载"];
    readonly downloadedStatus: readonly ["Downloaded", "已下载"];
    readonly pausedStatus: readonly ["Stopped", "已停止"];
    readonly failedDownload: readonly ["Download failed", "下载失败"];
    readonly downloadRunning: readonly ["Downloading", "正在下载"];
    readonly transfersTitle: readonly ["Transfers", "下载任务"];
    readonly selectedEngine: readonly ["Selected engine", "当前选用引擎"];
    readonly noEngine: readonly ["No engine selected", "尚未选择引擎"];
    readonly useEngine: readonly ["Use version", "使用此版本"];
    readonly installEngineTitle: readonly ["Install MoE4All", "安装 MoE4All 引擎"];
    readonly localEngineTitle: readonly ["Use an existing installation", "使用已有引擎"];
    readonly localEnginePath: readonly ["Executable, folder or release ZIP", "可执行文件、目录或发行版 ZIP"];
    readonly adoptEngine: readonly ["Import engine", "导入引擎"];
    readonly installedVersions: readonly ["Installed versions", "已安装版本"];
    readonly upToDate: readonly ["Latest version selected", "已选用最新版本"];
    readonly newVersion: readonly ["Update available", "有可用更新"];
    readonly selectedVersionHint: readonly ["Select another version before deleting this one.", "先选用其他版本，再删除此版本。"];
    readonly removeEngineTitle: readonly ["Delete engine version?", "删除此引擎版本？"];
    readonly removeEngineBody: readonly ["This removes the selected installation directory. Models outside it are kept.", "将删除该版本的安装目录。目录外的模型不受影响。"];
    readonly stopEngineTitle: readonly ["Stop the engine?", "停止引擎？"];
    readonly stopEngineBody: readonly ["Active requests will be interrupted and GPU memory released.", "当前请求将中断，并释放引擎占用的显存。"];
    readonly restartEngineTitle: readonly ["Apply settings and restart?", "应用设置并重启？"];
    readonly restartEngineBody: readonly ["The engine will reload the selected model. Active requests will be interrupted.", "引擎将按当前配置重新加载模型，当前请求会中断。"];
    readonly stopEngineAction: readonly ["Stop engine", "停止引擎"];
    readonly restartEngineAction: readonly ["Apply and restart", "应用并重启"];
    readonly testConnection: readonly ["Test connection", "测试连接"];
    readonly saveConnect: readonly ["Save and connect", "保存并连接"];
    readonly saveStart: readonly ["Save and start", "保存并启动"];
    readonly savedNextStart: readonly ["Saved for the next start", "已保存，下次启动生效"];
    readonly pendingRestart: readonly ["Saved settings are waiting for a restart.", "配置已保存，等待重启生效。"];
    readonly pendingEdits: readonly ["Unsaved changes", "有未保存的更改"];
    readonly startNeeded: readonly ["Select an engine and model to start.", "准备好引擎与模型后即可启动。"];
    readonly connectionOk: readonly ["Connection successful", "连接成功"];
    readonly connectionFailed: readonly ["No response from this endpoint", "此地址尚未响应"];
    readonly controlUnavailable: readonly ["The plugin service is unreachable. Reconnecting...", "暂时无法连接插件服务，正在重新连接…"];
    readonly runtimeOutput: readonly ["Engine output", "引擎输出"];
    readonly noOutput: readonly ["No engine output yet", "暂无引擎输出"];
    readonly copyOutput: readonly ["Copy output", "复制输出"];
    readonly copied: readonly ["Copied", "已复制"];
    readonly refreshStatus: readonly ["Refresh status", "刷新状态"];
    readonly diagnosticSettings: readonly ["Startup & diagnostics", "启动与诊断设置"];
    readonly chooseAttachment: readonly ["Choose file", "选择文件"];
    readonly attachmentAuto: readonly ["Detected alongside the model", "已探测到同家族文件"];
    readonly modelSelectedNotice: readonly ["Model selected. Save to apply.", "模型已选用，保存后生效。"];
    readonly engineSelectedNotice: readonly ["Engine selected. Save to apply.", "引擎已选用，保存后生效。"];
    readonly selectDestination: readonly ["Choose a model storage directory first.", "请先选择模型存放目录。"];
    readonly missingModelError: readonly ["Choose a language model first.", "请先选择语言模型。"];
    readonly missingEngineError: readonly ["Install or select an engine first.", "请先安装或选择引擎。"];
    readonly invalidTokens: readonly ["Enter a positive token count, such as 32768 or 32k.", "请输入有效的正数 Token 数量，例如 32768 或 32k。"];
    readonly importError: readonly ["No matching GGUF was found at this path.", "此路径下未找到对应类型的 GGUF。"];
    readonly invalidExtra: readonly ["Use a JSON array of strings. Set the model and common options in their fields, not here.", "请输入字符串 JSON 数组；模型路径与常用设置请在对应控件中填写，不要重复覆盖。"];
    readonly discardTitle: readonly ["Discard unsaved changes?", "放弃未保存的更改？"];
    readonly discardAction: readonly ["Discard changes", "放弃更改"];
    readonly doneAction: readonly ["Done", "完成"];
    readonly detailLabel: readonly ["Details", "详情"];
    readonly blankAuto: readonly ["Leave blank for automatic", "留空为自动"];
    readonly apiKeyHelp: readonly ["Name of the environment variable containing the API key.", "填写保存 API key 的环境变量名称。"];
    readonly networkHelp: readonly ["Local access uses 127.0.0.1. LAN endpoints need remote access enabled.", "本机访问使用 127.0.0.1；局域网地址需允许远程连接。"];
    readonly moreSettings: readonly ["More settings", "更多设置"];
    readonly clearSelection: readonly ["Clear selection", "取消选用"];
    readonly currentEndpoint: readonly ["Service endpoint", "服务地址"];
    readonly returnedModels: readonly ["Available in DSH", "DSH 可用模型"];
    readonly startupElapsed: readonly ["Elapsed", "已用时"];
    readonly progressChecking: readonly ["Checking release", "正在检查发行版"];
    readonly progressVerifying: readonly ["Verifying download", "正在校验下载"];
    readonly progressExtracting: readonly ["Extracting engine", "正在解压引擎"];
    readonly progressFinalizing: readonly ["Finishing installation", "正在完成安装"];
    readonly stopTransfer: readonly ["Stop download", "停止下载"];
    readonly externalProcessHelp: readonly ["Connect to its actual address, or stop it before starting another engine.", "请连接该进程的实际地址，或先将其停止。"];
};
export type WorkspaceKey = keyof typeof copy;
export declare const workspaceEn: Record<WorkspaceKey, string>;
export declare const workspaceZh: Record<WorkspaceKey, string>;
export {};
//# sourceMappingURL=workspace-copy.d.ts.map