const copy = {
    runTab: ['Run', '运行'],
    parallel: ['Concurrent slots', '并发会话数'],
    modelsTab: ['Model library', '模型库'],
    rescanModels: ['Rescan local models', '重新扫描本地模型'],
    openModelSource: ['Open model source', '打开模型来源'],
    advancedOverride: ['Manual values override the selected preset.', '手动填写的参数优先于自动策略。'],
    enginesTab: ['Engine versions', '引擎版本'],
    diagnosticsTab: ['Diagnostics', '诊断'],
    localRun: ['Run on this computer', '在本机运行'],
    existingService: ['Connect to a service', '连接已有服务'],
    notConfigured: ['Not configured', '尚未配置'],
    readyStatus: ['Ready', '已就绪'],
    startingStatus: ['Starting', '正在启动'],
    stoppedStatus: ['Stopped', '未运行'],
    failedStatus: ['Startup failed', '启动失败'],
    checkingStatus: ['Checking connection', '正在检查连接'],
    busyStatus: ['Confirmation needed', '等待确认'],
    duplicateStatus: ['Engine already running elsewhere', '检测到其他引擎进程'],
    pluginOwned: ['Started here', '由插件启动'],
    externalOwned: ['Existing service', '已有服务'],
    setupTitle: ['Get ready to run', '准备开始'],
    stepEngine: ['Install an engine', '准备引擎'],
    stepModel: ['Choose a model', '选择模型'],
    stepStart: ['Start chatting', '启动使用'],
    modelEmpty: ['No model selected', '尚未选择模型'],
    selectedModelTitle: ['Selected model', '当前模型'],
    browseLibrary: ['Choose a model', '选择模型'],
    importModel: ['Add local model', '添加本地模型'],
    useSelected: ['Use model', '使用此模型'],
    usingModel: ['Selected', '已选用'],
    changeModel: ['Change', '更换'],
    optionalFeatures: ['Optional capabilities', '可选能力'],
    essential: ['Common settings', '常用设置'],
    performance: ['Performance preset', '性能策略'],
    balancedLabel: ['Balanced', '稳健自动'],
    performanceLabel: ['Performance', '激进自动'],
    balancedHelp: ['Uses currently available memory with headroom.', '按当前空余内存与显存分配，保留余量。'],
    performanceHelp: ['Uses larger budgets based on total memory.', '按总内存与总显存规划更大的预算。'],
    automatic: ['Automatic', '自动'],
    startupPolicy: ['When DSH opens', '打开 DSH 时'],
    askStart: ['Ask before starting', '询问是否启动'],
    autoStart: ['Start automatically', '自动启动'],
    resourcesHelp: ['A second confirmation is required when resources fall below the threshold.', '资源低于警戒线时，启动仍需再次确认。'],
    advancedOptions: ['Advanced parameters', '高级参数'],
    memoryCompute: ['Memory & compute', '内存与计算'],
    deviceLabel: ['GPU device', 'GPU 设备'],
    ramLabel: ['RAM budget', 'RAM 预算'],
    vramLabel: ['VRAM budget', 'VRAM 预算'],
    threadsLabel: ['CPU threads', 'CPU 线程'],
    batchLabel: ['Prefill micro-batch', 'Prefill Ubatch'],
    splitterLabel: ['Dispatch cap', 'Dispatch 上限'],
    cacheSection: ['Conversation cache', '会话缓存'],
    cacheEnabled: ['Reuse conversations from SSD', '复用 SSD 会话缓存'],
    networkSection: ['Network & connection', '网络与连接'],
    samplingSection: ['Generation defaults', '生成默认值'],
    temperatureLabel: ['Temperature', '温度'],
    customArguments: ['Additional engine arguments', '额外引擎参数'],
    launchPreview: ['Launch command', '启动命令预览'],
    modelDirectoryLabel: ['Model storage', '模型存放目录'],
    searchModels: ['Search models or quantization', '搜索模型或量化'],
    filterAll: ['All', '全部'],
    filterLocal: ['On this computer', '本地'],
    filterRecommended: ['Recommended', '推荐'],
    availableLocal: ['Local', '本地可用'],
    incompleteModel: ['Missing shards', '分片不完整'],
    noMatches: ['No matching models', '没有匹配的模型'],
    noLocalModels: ['No local models yet', '尚未添加本地模型'],
    importPath: ['File or folder path', '文件或目录路径'],
    addPath: ['Add', '添加'],
    modelRoleMain: ['Language model', '语言模型'],
    modelRoleVision: ['Vision', '视觉'],
    modelRoleMtp: ['MTP', 'MTP'],
    modelRoleEmbedding: ['Embedding', 'Embedding'],
    downloadAction: ['Download', '下载'],
    continueDownload: ['Continue download', '继续下载'],
    downloadedStatus: ['Downloaded', '已下载'],
    pausedStatus: ['Stopped', '已停止'],
    failedDownload: ['Download failed', '下载失败'],
    downloadRunning: ['Downloading', '正在下载'],
    transfersTitle: ['Transfers', '下载任务'],
    selectedEngine: ['Selected engine', '当前选用引擎'],
    noEngine: ['No engine selected', '尚未选择引擎'],
    useEngine: ['Use version', '使用此版本'],
    installEngineTitle: ['Install MoE4All', '安装 MoE4All 引擎'],
    localEngineTitle: ['Use an existing installation', '使用已有引擎'],
    localEnginePath: ['Executable, folder or release ZIP', '可执行文件、目录或发行版 ZIP'],
    adoptEngine: ['Import engine', '导入引擎'],
    installedVersions: ['Installed versions', '已安装版本'],
    upToDate: ['Latest version selected', '已选用最新版本'],
    newVersion: ['Update available', '有可用更新'],
    selectedVersionHint: ['Select another version before deleting this one.', '先选用其他版本，再删除此版本。'],
    removeEngineTitle: ['Delete engine version?', '删除此引擎版本？'],
    removeEngineBody: ['This removes the selected installation directory. Models outside it are kept.', '将删除该版本的安装目录。目录外的模型不受影响。'],
    stopEngineTitle: ['Stop the engine?', '停止引擎？'],
    stopEngineBody: ['Active requests will be interrupted and GPU memory released.', '当前请求将中断，并释放引擎占用的显存。'],
    restartEngineTitle: ['Apply settings and restart?', '应用设置并重启？'],
    restartEngineBody: ['The engine will reload the selected model. Active requests will be interrupted.', '引擎将按当前配置重新加载模型，当前请求会中断。'],
    stopEngineAction: ['Stop engine', '停止引擎'],
    restartEngineAction: ['Apply and restart', '应用并重启'],
    testConnection: ['Test connection', '测试连接'],
    saveConnect: ['Save and connect', '保存并连接'],
    saveStart: ['Save and start', '保存并启动'],
    savedNextStart: ['Saved for the next start', '已保存，下次启动生效'],
    pendingRestart: ['Saved settings are waiting for a restart.', '配置已保存，等待重启生效。'],
    pendingEdits: ['Unsaved changes', '有未保存的更改'],
    startNeeded: ['Select an engine and model to start.', '准备好引擎与模型后即可启动。'],
    connectionOk: ['Connection successful', '连接成功'],
    connectionFailed: ['No response from this endpoint', '此地址尚未响应'],
    controlUnavailable: ['The plugin service is unreachable. Reconnecting...', '暂时无法连接插件服务，正在重新连接…'],
    runtimeOutput: ['Engine output', '引擎输出'],
    noOutput: ['No engine output yet', '暂无引擎输出'],
    copyOutput: ['Copy output', '复制输出'],
    copied: ['Copied', '已复制'],
    refreshStatus: ['Refresh status', '刷新状态'],
    diagnosticSettings: ['Startup & diagnostics', '启动与诊断设置'],
    chooseAttachment: ['Choose file', '选择文件'],
    attachmentAuto: ['Detected alongside the model', '已探测到同家族文件'],
    modelSelectedNotice: ['Model selected. Save to apply.', '模型已选用，保存后生效。'],
    engineSelectedNotice: ['Engine selected. Save to apply.', '引擎已选用，保存后生效。'],
    selectDestination: ['Choose a model storage directory first.', '请先选择模型存放目录。'],
    missingModelError: ['Choose a language model first.', '请先选择语言模型。'],
    missingEngineError: ['Install or select an engine first.', '请先安装或选择引擎。'],
    invalidTokens: ['Enter a positive token count, such as 32768 or 32k.', '请输入有效的正数 Token 数量，例如 32768 或 32k。'],
    importError: ['No matching GGUF was found at this path.', '此路径下未找到对应类型的 GGUF。'],
    invalidExtra: ['Use a JSON array of strings. Set the model and common options in their fields, not here.', '请输入字符串 JSON 数组；模型路径与常用设置请在对应控件中填写，不要重复覆盖。'],
    discardTitle: ['Discard unsaved changes?', '放弃未保存的更改？'],
    discardAction: ['Discard changes', '放弃更改'],
    doneAction: ['Done', '完成'],
    detailLabel: ['Details', '详情'],
    blankAuto: ['Leave blank for automatic', '留空为自动'],
    apiKeyHelp: ['Name of the environment variable containing the API key.', '填写保存 API key 的环境变量名称。'],
    networkHelp: ['Local access uses 127.0.0.1. LAN endpoints need remote access enabled.', '本机访问使用 127.0.0.1；局域网地址需允许远程连接。'],
    moreSettings: ['More settings', '更多设置'],
    clearSelection: ['Clear selection', '取消选用'],
    currentEndpoint: ['Service endpoint', '服务地址'],
    returnedModels: ['Available in DSH', 'DSH 可用模型'],
    startupElapsed: ['Elapsed', '已用时'],
    progressChecking: ['Checking release', '正在检查发行版'],
    progressVerifying: ['Verifying download', '正在校验下载'],
    progressExtracting: ['Extracting engine', '正在解压引擎'],
    progressFinalizing: ['Finishing installation', '正在完成安装'],
    stopTransfer: ['Stop download', '停止下载'],
    externalProcessHelp: ['Connect to its actual address, or stop it before starting another engine.', '请连接该进程的实际地址，或先将其停止。'],
};
export const workspaceEn = Object.fromEntries(Object.entries(copy).map(([key, value]) => [key, value[0]]));
export const workspaceZh = Object.fromEntries(Object.entries(copy).map(([key, value]) => [key, value[1]]));
//# sourceMappingURL=workspace-copy.js.map