import type { Context } from '@deepseek-ai/cordis';
import z from '@deepseek-ai/schemastery';
import { type EngineConfig } from './engine-controller.js';
import { type ModelProviderConfig } from './model-provider.js';
export declare const name = "moe4all-engine";
export declare const inject: string[];
export interface Config extends EngineConfig, ModelProviderConfig {
}
export declare const Config: z<Schemastery.ObjectS<{
    mode: z<"connect" | "auto" | "managed", "connect" | "auto" | "managed">;
    protocol: z<"http" | "https", "http" | "https">;
    host: z<string, string>;
    port: z<number, number>;
    apiBasePath: z<string, string>;
    endpoint: z<string, string>;
    executable: z<string, string>;
    arguments: z<string[], string[]>;
    workingDirectory: z<string, string>;
    apiKeyEnv: z<string, string>;
    allowRemoteEndpoint: z<boolean, boolean>;
    processNames: z<string[], string[]>;
    minimumFreeRamFraction: z<number, number>;
    minimumFreeVramFraction: z<number, number>;
    promptWhenBusy: z<boolean, boolean>;
    resourceProbeTimeoutMs: z<number, number>;
    startupTimeoutMs: z<number, number>;
    healthTimeoutMs: z<number, number>;
    pollIntervalMs: z<number, number>;
    shutdownTimeoutMs: z<number, number>;
    stopOnUnload: z<boolean, boolean>;
    logOutput: z<boolean, boolean>;
    contextWindow: z<number, number>;
    maxTokens: z<number, number>;
    vision: z<boolean, boolean>;
    excludeModelNameContains: z<string[], string[]>;
    modelRefreshIntervalMs: z<number, number>;
    modelDiscoveryTimeoutMs: z<number, number>;
}>, Schemastery.ObjectT<{
    mode: z<"connect" | "auto" | "managed", "connect" | "auto" | "managed">;
    protocol: z<"http" | "https", "http" | "https">;
    host: z<string, string>;
    port: z<number, number>;
    apiBasePath: z<string, string>;
    endpoint: z<string, string>;
    executable: z<string, string>;
    arguments: z<string[], string[]>;
    workingDirectory: z<string, string>;
    apiKeyEnv: z<string, string>;
    allowRemoteEndpoint: z<boolean, boolean>;
    processNames: z<string[], string[]>;
    minimumFreeRamFraction: z<number, number>;
    minimumFreeVramFraction: z<number, number>;
    promptWhenBusy: z<boolean, boolean>;
    resourceProbeTimeoutMs: z<number, number>;
    startupTimeoutMs: z<number, number>;
    healthTimeoutMs: z<number, number>;
    pollIntervalMs: z<number, number>;
    shutdownTimeoutMs: z<number, number>;
    stopOnUnload: z<boolean, boolean>;
    logOutput: z<boolean, boolean>;
    contextWindow: z<number, number>;
    maxTokens: z<number, number>;
    vision: z<boolean, boolean>;
    excludeModelNameContains: z<string[], string[]>;
    modelRefreshIntervalMs: z<number, number>;
    modelDiscoveryTimeoutMs: z<number, number>;
}>>;
export declare function apply(ctx: Context, config: Config): () => Promise<void>;
declare const plugin: {
    name: string;
    inject: string[];
    Config: z<Schemastery.ObjectS<{
        mode: z<"connect" | "auto" | "managed", "connect" | "auto" | "managed">;
        protocol: z<"http" | "https", "http" | "https">;
        host: z<string, string>;
        port: z<number, number>;
        apiBasePath: z<string, string>;
        endpoint: z<string, string>;
        executable: z<string, string>;
        arguments: z<string[], string[]>;
        workingDirectory: z<string, string>;
        apiKeyEnv: z<string, string>;
        allowRemoteEndpoint: z<boolean, boolean>;
        processNames: z<string[], string[]>;
        minimumFreeRamFraction: z<number, number>;
        minimumFreeVramFraction: z<number, number>;
        promptWhenBusy: z<boolean, boolean>;
        resourceProbeTimeoutMs: z<number, number>;
        startupTimeoutMs: z<number, number>;
        healthTimeoutMs: z<number, number>;
        pollIntervalMs: z<number, number>;
        shutdownTimeoutMs: z<number, number>;
        stopOnUnload: z<boolean, boolean>;
        logOutput: z<boolean, boolean>;
        contextWindow: z<number, number>;
        maxTokens: z<number, number>;
        vision: z<boolean, boolean>;
        excludeModelNameContains: z<string[], string[]>;
        modelRefreshIntervalMs: z<number, number>;
        modelDiscoveryTimeoutMs: z<number, number>;
    }>, Schemastery.ObjectT<{
        mode: z<"connect" | "auto" | "managed", "connect" | "auto" | "managed">;
        protocol: z<"http" | "https", "http" | "https">;
        host: z<string, string>;
        port: z<number, number>;
        apiBasePath: z<string, string>;
        endpoint: z<string, string>;
        executable: z<string, string>;
        arguments: z<string[], string[]>;
        workingDirectory: z<string, string>;
        apiKeyEnv: z<string, string>;
        allowRemoteEndpoint: z<boolean, boolean>;
        processNames: z<string[], string[]>;
        minimumFreeRamFraction: z<number, number>;
        minimumFreeVramFraction: z<number, number>;
        promptWhenBusy: z<boolean, boolean>;
        resourceProbeTimeoutMs: z<number, number>;
        startupTimeoutMs: z<number, number>;
        healthTimeoutMs: z<number, number>;
        pollIntervalMs: z<number, number>;
        shutdownTimeoutMs: z<number, number>;
        stopOnUnload: z<boolean, boolean>;
        logOutput: z<boolean, boolean>;
        contextWindow: z<number, number>;
        maxTokens: z<number, number>;
        vision: z<boolean, boolean>;
        excludeModelNameContains: z<string[], string[]>;
        modelRefreshIntervalMs: z<number, number>;
        modelDiscoveryTimeoutMs: z<number, number>;
    }>>;
    apply: typeof apply;
};
export default plugin;
export { EngineController, detectRunningEngines, endpointFromConfig, parseTasklistCsv, probeEngineResources, probeHealth, resolveEngineExecutable, validateEndpoint, } from './engine-controller.js';
export type { EngineConfig, EngineLogger, LaunchMode, ResourceSnapshot, RunningProcess, } from './engine-controller.js';
export { discoverModels, ModelProviderBridge, providerProfile } from './model-provider.js';
export type { DiscoveredModel, LoaderLike, ModelProviderConfig } from './model-provider.js';
//# sourceMappingURL=index.d.ts.map