import type { Context } from '@deepseek-ai/cordis';
import z from '@deepseek-ai/schemastery';
import { type EngineConfig } from './engine-controller.js';
import { type ModelProviderConfig } from './model-provider.js';
export declare const name = "moe4all-engine";
export declare const inject: string[];
export declare const SETTINGS_NAMESPACE: import("@deepseek-ai/dsh-settings").SettingsNamespace;
export interface Config extends EngineConfig, ModelProviderConfig {
    modelDirectory?: string;
}
export declare const Config: z<Schemastery.ObjectS<{
    mode: z<"connect" | "prompt" | "auto" | "managed", "connect" | "prompt" | "auto" | "managed">;
    protocol: z<"http" | "https", "http" | "https">;
    host: z<string, string>;
    port: z<number, number>;
    apiBasePath: z<string, string>;
    endpoint: z<string, string>;
    executable: z<string, string>;
    arguments: z<string[], string[]>;
    workingDirectory: z<string, string>;
    apiKeyEnv: z<string, string>;
    allowRemoteEndpoint: z<boolean, boolean>;
    processNames: z<string[], string[]>;
    minimumFreeRamFraction: z<number, number>;
    minimumFreeVramFraction: z<number, number>;
    promptWhenBusy: z<boolean, boolean>;
    resourceProbeTimeoutMs: z<number, number>;
    startupTimeoutMs: z<number, number>;
    healthTimeoutMs: z<number, number>;
    pollIntervalMs: z<number, number>;
    shutdownTimeoutMs: z<number, number>;
    stopOnUnload: z<boolean, boolean>;
    logOutput: z<boolean, boolean>;
    contextWindow: z<number, number>;
    maxTokens: z<number, number>;
    modelDirectory: z<string, string>;
    vision: z<boolean, boolean>;
    excludeModelNameContains: z<string[], string[]>;
    modelRefreshIntervalMs: z<number, number>;
    modelDiscoveryTimeoutMs: z<number, number>;
}>, Schemastery.ObjectT<{
    mode: z<"connect" | "prompt" | "auto" | "managed", "connect" | "prompt" | "auto" | "managed">;
    protocol: z<"http" | "https", "http" | "https">;
    host: z<string, string>;
    port: z<number, number>;
    apiBasePath: z<string, string>;
    endpoint: z<string, string>;
    executable: z<string, string>;
    arguments: z<string[], string[]>;
    workingDirectory: z<string, string>;
    apiKeyEnv: z<string, string>;
    allowRemoteEndpoint: z<boolean, boolean>;
    processNames: z<string[], string[]>;
    minimumFreeRamFraction: z<number, number>;
    minimumFreeVramFraction: z<number, number>;
    promptWhenBusy: z<boolean, boolean>;
    resourceProbeTimeoutMs: z<number, number>;
    startupTimeoutMs: z<number, number>;
    healthTimeoutMs: z<number, number>;
    pollIntervalMs: z<number, number>;
    shutdownTimeoutMs: z<number, number>;
    stopOnUnload: z<boolean, boolean>;
    logOutput: z<boolean, boolean>;
    contextWindow: z<number, number>;
    maxTokens: z<number, number>;
    modelDirectory: z<string, string>;
    vision: z<boolean, boolean>;
    excludeModelNameContains: z<string[], string[]>;
    modelRefreshIntervalMs: z<number, number>;
    modelDiscoveryTimeoutMs: z<number, number>;
}>>;
export declare function apply(ctx: Context, config: Config): () => Promise<void>;
declare const plugin: {
    name: string;
    inject: string[];
    Config: z<Schemastery.ObjectS<{
        mode: z<"connect" | "prompt" | "auto" | "managed", "connect" | "prompt" | "auto" | "managed">;
        protocol: z<"http" | "https", "http" | "https">;
        host: z<string, string>;
        port: z<number, number>;
        apiBasePath: z<string, string>;
        endpoint: z<string, string>;
        executable: z<string, string>;
        arguments: z<string[], string[]>;
        workingDirectory: z<string, string>;
        apiKeyEnv: z<string, string>;
        allowRemoteEndpoint: z<boolean, boolean>;
        processNames: z<string[], string[]>;
        minimumFreeRamFraction: z<number, number>;
        minimumFreeVramFraction: z<number, number>;
        promptWhenBusy: z<boolean, boolean>;
        resourceProbeTimeoutMs: z<number, number>;
        startupTimeoutMs: z<number, number>;
        healthTimeoutMs: z<number, number>;
        pollIntervalMs: z<number, number>;
        shutdownTimeoutMs: z<number, number>;
        stopOnUnload: z<boolean, boolean>;
        logOutput: z<boolean, boolean>;
        contextWindow: z<number, number>;
        maxTokens: z<number, number>;
        modelDirectory: z<string, string>;
        vision: z<boolean, boolean>;
        excludeModelNameContains: z<string[], string[]>;
        modelRefreshIntervalMs: z<number, number>;
        modelDiscoveryTimeoutMs: z<number, number>;
    }>, Schemastery.ObjectT<{
        mode: z<"connect" | "prompt" | "auto" | "managed", "connect" | "prompt" | "auto" | "managed">;
        protocol: z<"http" | "https", "http" | "https">;
        host: z<string, string>;
        port: z<number, number>;
        apiBasePath: z<string, string>;
        endpoint: z<string, string>;
        executable: z<string, string>;
        arguments: z<string[], string[]>;
        workingDirectory: z<string, string>;
        apiKeyEnv: z<string, string>;
        allowRemoteEndpoint: z<boolean, boolean>;
        processNames: z<string[], string[]>;
        minimumFreeRamFraction: z<number, number>;
        minimumFreeVramFraction: z<number, number>;
        promptWhenBusy: z<boolean, boolean>;
        resourceProbeTimeoutMs: z<number, number>;
        startupTimeoutMs: z<number, number>;
        healthTimeoutMs: z<number, number>;
        pollIntervalMs: z<number, number>;
        shutdownTimeoutMs: z<number, number>;
        stopOnUnload: z<boolean, boolean>;
        logOutput: z<boolean, boolean>;
        contextWindow: z<number, number>;
        maxTokens: z<number, number>;
        modelDirectory: z<string, string>;
        vision: z<boolean, boolean>;
        excludeModelNameContains: z<string[], string[]>;
        modelRefreshIntervalMs: z<number, number>;
        modelDiscoveryTimeoutMs: z<number, number>;
    }>>;
    apply: typeof apply;
};
export default plugin;
export { EngineController, detectRunningEngines, effectiveLaunchMode, endpointFromConfig, parseTasklistCsv, probeEngineResources, probeHealth, resolveEngineExecutable, validateEndpoint, } from './engine-controller.js';
export type { EffectiveLaunchMode, EngineConfig, EngineLogger, EnginePhase, EngineRuntimeStatus, EngineStartResult, LaunchMode, ResourceSnapshot, RunningProcess, } from './engine-controller.js';
export { EngineReleaseManager, releaseFromTag, selectRelease } from './engine-release.js';
export type { EngineBootstrapResult, EngineInstallProgress, EngineInstallStage, EngineReleaseStatus, InstalledEngine, SelectedRelease } from './engine-release.js';
export { ENGINE_PATHS, isLoopbackRequest, makeEngineRoutes } from './host-routes.js';
export { ModelDownloadManager, RECOMMENDED_MODELS } from './model-download.js';
export type { ModelDownloadProgress, RecommendedModel, RecommendedModelKind } from './model-download.js';
export { discoverModels, ModelProviderBridge, providerProfile } from './model-provider.js';
export type { DiscoveredModel, ModelProviderConfig, ProviderSettingsLike } from './model-provider.js';
//# sourceMappingURL=index.d.ts.map